export type A2SectionId = 'entry' | 'patterns' | 'scripture' | 'reflection' | 'go-deeper' | 'practice' | 'carry-forward';
export type A2Section = Readonly<{id:A2SectionId;eyebrow:string;title:string;paragraphs:readonly string[];prompt?:string}>;

export const A2_SECTIONS: readonly A2Section[] = [
 {id:'entry',eyebrow:'AWAKEN · 02',title:'Catch Yourself Being You',paragraphs:['A moment can feel instantaneous: something happens, and then you respond.','But when you slow it down, the response often has a before. You noticed something. It meant something to you. Something mattered. An impulse formed. Then you acted.','You do not need to find every step. Today we are looking for one more.']},
 {id:'patterns',eyebrow:'SLOW THE MOMENT DOWN',title:'What happened just before what you did?',paragraphs:['Stay with one situation rather than collecting examples from your life. Name only what you can honestly observe. If a step is unclear, leave it unclear.','The framework is backstage support, not a conclusion about you. Hardwired and held loosely.']},
 {id:'scripture',eyebrow:'A MOMENT TO CONSIDER',title:'Seeing creates possibility.',paragraphs:['For if anyone is a hearer of the word and not a doer, he is like a man looking at his natural face in a mirror. For he sees himself, and goes away, and immediately forgets what kind of man he was.','James uses a mirror to describe honest seeing. Awareness is not condemnation. It gives you the possibility of remaining present to something that previously passed unnoticed.']},
 {id:'reflection',eyebrow:'YOUR MOMENT',title:'What came before the response?',paragraphs:['Look only at the moment you are carrying. Perhaps you noticed a thought, expectation, body sensation, desire, fear, or impulse before you acted. Perhaps you only know that something changed.','Do not turn one observation into a pattern. One moment can simply be one moment.'],prompt:'What is one thing you can see now that happened before your response?'},
 {id:'go-deeper',eyebrow:'A SMALL PRACTICE',title:'Notice. Name. Stay.',paragraphs:['Notice that something changed. Name only what you can actually see. Stay with it long enough to let the moment become clearer.','You may ask God what He wants you to see and leave the question open. You do not need to manufacture an answer.']},
 {id:'practice',eyebrow:'IN YOUR DAY',title:'Find the before.',paragraphs:['When you catch a response in real time, see whether you can notice what happened immediately before it. One step is enough.','As this becomes familiar, you may sometimes notice several steps at once. Do not try to process all of them. Take one thing through the whole process.']},
 {id:'carry-forward',eyebrow:'CARRY FORWARD',title:'Automatic is becoming visible.',paragraphs:['The response may still happen quickly, but it no longer has to be a blank space. You have begun to see that something was happening before it.','Next, we will separate what you noticed yourself doing from what you may be tempted to conclude about who you are.']},
] as const;
