export type NewAwakenSectionId = 'entry' | 'teaching' | 'trace' | 'reframe' | 'reflection' | 'practice' | 'carry-forward';
export type NewAwakenSection = Readonly<{ id: NewAwakenSectionId; eyebrow: string; title: string; paragraphs: readonly string[]; prompt?: string }>;

export const A3_SECTIONS: readonly NewAwakenSection[] = [
 {id:'entry',eyebrow:'AWAKEN · 03',title:'A Response Is Not an Identity',paragraphs:['Once you can see a response, it is easy to turn observation into a label: “I am controlling.” “I am avoidant.” “I am just an anxious person.”','Slow down. What you did in a moment is real, but it is not automatically the whole truth about who you are. Awaken asks for accuracy before interpretation.']},
 {id:'teaching',eyebrow:'DESCRIBE BEFORE YOU DEFINE',title:'Say what happened without turning it into who you are.',paragraphs:['“I withdrew when I felt exposed” is an observation. “I am a withdrawn person” is a conclusion. “I tried to control the conversation when I became uncertain” describes a moment. “I am controlling” turns that moment into an identity.','A response can be important without becoming a verdict. Second Corinthians 5:17 leaves room for a deeper identity in Christ while we tell the truth about what still needs formation.','One moment is not a pattern. Several moments may eventually reveal something worth noticing, but the participant—not the system—should be allowed to see that connection.']},
 {id:'trace',eyebrow:'HOLD IT LOOSELY',title:'Put the observation beside the conclusion.',paragraphs:['Start with what you actually did in the moment. Then notice what you are tempted to call yourself because of it. Keep the two statements separate.','You may discover that the conclusion is accurate language for a repeated behavior. You may discover it is too broad. You may simply remain unsure. Nothing here requires a label.']},
 {id:'reflection',eyebrow:'YOUR WORDS',title:'What changes when you describe instead of define?',paragraphs:['You are not trying to make yourself sound better. You are trying to see more precisely. Precision creates room that a fixed identity statement does not.'],prompt:'What can you say accurately about this moment without making it the whole truth about you?'},
 {id:'practice',eyebrow:'IN YOUR DAY',title:'Listen for identity language.',paragraphs:['Notice phrases such as “I’m just like that,” “That’s who I am,” or “I can’t help it.” Pause before arguing with them. Ask whether you are naming your identity or describing something you have noticed yourself doing.','The difference matters because something you can observe is also something you can become aware of while it is happening.']},
 {id:'carry-forward',eyebrow:'CARRY FORWARD',title:'You are learning to see without sentencing yourself.',paragraphs:['A response can be real, consequential, and worth changing without becoming the definition of the person who made it.','Now we can return to one real moment and look more closely at the steps that were moving beneath the visible response.']},
];

export const A4_SECTIONS: readonly NewAwakenSection[] = [
 {id:'entry',eyebrow:'AWAKEN · 04',title:'See the Moment in Slow Motion',paragraphs:['You began with a response. Now look backward. Before that response, what had you noticed? What did you think was happening? What did you expect? What did you want? What felt important or threatened?','You will not need an answer to every question. We are not assembling a diagnosis. We are discovering that what once looked instantaneous had a sequence.']},
 {id:'teaching',eyebrow:'THE INVISIBLE BEFORE',title:'Many things can happen before a response.',paragraphs:['An event reaches you. You notice something about it. Meaning begins to form. You may expect something, want something, fear something, or feel something in your body. An impulse takes shape. Eventually something becomes visible in what you say or do.','The framework helps us know where to look, but it does not tell us what must be there. Hardwired and held loosely.','You do not do all of these through one process. When something meaningful surfaces, stay coherently with one thing.']},
 {id:'trace',eyebrow:'ONE REAL MOMENT',title:'Take one thing through the process.',paragraphs:['Stay with the same situation you have been carrying. We will ask only what helps you see it more clearly. Some questions can be handled directly by the experience. When your answer genuinely changes what would be useful next, the guide can adapt behind the scenes.','“I’m not sure” is a complete answer. Repeating yourself is often a sign that there may be nothing more to uncover right now.']},
 {id:'reflection',eyebrow:'LOOK AT WHAT BECAME VISIBLE',title:'Your response had a before.',paragraphs:['You may have noticed an expectation, desire, fear, interpretation, sensation, impulse, or something else entirely. You may have noticed only one new step. That is enough.','The goal was never to produce an impressive insight. It was to see something that had previously happened without your awareness.'],prompt:'What can you see now that you could not see when the moment first happened?'},
 {id:'practice',eyebrow:'POSSIBILITY',title:'Awareness gives you somewhere to be present.',paragraphs:['If you can notice even one step before the response, the sequence is no longer completely invisible. There is now a place where awareness can enter.','You do not have to force a different response yet. Awaken has given you possibility where there was only automatic movement before.']},
 {id:'carry-forward',eyebrow:'AWAKEN · COMPLETE',title:'You saw what was already there.',paragraphs:['Your response did not begin with your response. There was more happening in the moment than you could see—and now you can see more of it.','This cycle is complete. You can continue into See Clearly, or return later and take a different situation through Awaken. A new moment starts with a clean active workspace; completed moments can remain available to you.','Different situations may reveal different things. RTS does not need to declare a pattern across them. If you ever want to look across selected moments, you can decide to do that and notice what you see.']},
];
