import type { A1SectionId } from '../../../../domain/deep-dive';

export type A1Section = Readonly<{ id: A1SectionId; eyebrow: string; title: string; paragraphs: readonly string[]; prompt?: string; reveal?: { label: string; text: string }; }>;

export const A1_SECTIONS: readonly A1Section[] = [
  { id:'entry', eyebrow:'AWAKEN · 01', title:'Pay Attention', paragraphs:['Your response did not begin with your response.','Before the thing you said, did, avoided, fixed, controlled, or withdrew from, something was already happening in you. Awaken begins by slowing one ordinary moment down enough to see it.'] },
  { id:'moment', eyebrow:'START WITH YOUR LIFE', title:'One ordinary moment is enough.', paragraphs:['Bring to mind something recent when something in you changed. It does not need to be dramatic. A message. A look. A change of plans. A compliment. A disappointment. A moment you suddenly wanted to explain, escape, fix, control, or hold back.','Do not explain it yet. Just find the moment.'] },
  { id:'outside-inside', eyebrow:'NOTICE THE DIFFERENCE', title:'Something happened around you. Something happened inside you.', paragraphs:['Those are not the same thing. The event belongs to the moment around you. Your tension, interpretation, desire, fear, urgency, relief, or impulse belongs to what began happening within you.','For now, the discovery is simply this: there was an inside to the moment.'] },
  { id:'teaching', eyebrow:'PAY ATTENTION', title:'Awareness creates a place that was not there before.', paragraphs:['Most responses feel immediate because the steps before them happen quickly. We experience the final reaction and assume that is where the story began.','Awaken slows the sequence down. You are not trying to fix yourself or find a hidden explanation. You are learning to notice one more thing that was already present.','Even one more noticed step creates possibility where there was only automatic response before.'], reveal:{label:'What counts as noticing?',text:'Anything you can honestly observe: a thought, sensation, expectation, desire, fear, impulse, interpretation, or uncertainty. “I’m not sure” is also honest awareness.'} },
  { id:'scripture', eyebrow:'SCRIPTURE · LUKE 6:45', title:'What comes out can reveal what is within.', paragraphs:['“The good man out of the good treasure of his heart brings out that which is good, and the evil man out of the evil treasure of his heart brings out that which is evil, for out of the abundance of the heart, his mouth speaks.”','Jesus points beneath the visible response. What comes out of us can invite attention to what was already moving within us.'] },
  { id:'reflection', eyebrow:'YOUR MOMENT', title:'Stay with what actually happened.', paragraphs:['Use one real situation. Do not search your history for proof of a pattern. We only need enough detail to stay grounded in this moment.'], prompt:'What happened, and what did you notice in yourself before or as you responded?' },
  { id:'go-deeper', eyebrow:'LOOK AGAIN', title:'The response was the end of a sequence, not the beginning.', paragraphs:['What could another person have observed? What was happening inside you that they could not see?','You do not need the whole sequence yet. If you can see one step that was invisible before, Awaken has already begun.'] },
  { id:'practice', eyebrow:'TRY IT IN REAL TIME', title:'Catch the change.', paragraphs:['During your day, notice the instant something in you changes. You might feel tension, relief, urgency, defensiveness, excitement, uncertainty, withdrawal, or the desire to take control.','Pause long enough to ask: “What just happened in me?” Then leave room for the answer without forcing one.','A simple prayer is enough: “God, help me see what is here.”'] },
  { id:'carry-forward', eyebrow:'CARRY FORWARD', title:'You saw one thing that used to happen unseen.', paragraphs:['That is enough for now. You are not collecting diagnoses or trying to explain your whole life. You are learning that a response has a before.','Next, we will slow the moment down further and see how one thing can lead to another before the visible response arrives.'] },
];
