import type { A1SectionId } from '../../../../domain/deep-dive';

export type A1Section = Readonly<{ id: A1SectionId; eyebrow: string; title: string; paragraphs: readonly string[]; prompt?: string; reveal?: { label: string; text: string }; }>;

export const A1_SECTIONS: readonly A1Section[] = [
  { id: 'entry', eyebrow: 'AWAKEN · 01', title: 'Start by paying attention', paragraphs: ['Where Did That Come From?', 'Before you try to change yourself, learn to notice what is already happening inside you. You are not being asked to fix anything yet.'] },
  { id: 'moment', eyebrow: 'START WITH A MOMENT', title: 'Notice what happens first', paragraphs: ['Imagine that message just appeared on your phone. Pause. What happens in you first?', 'These are examples, not a test: Nothing much. My stomach tightens. I wonder what I did wrong. I get irritated. I want to know what they want immediately. My mind starts replaying earlier conversations. Something else.'] },
  { id: 'outside-inside', eyebrow: 'NOTICE THE DIFFERENCE', title: 'The moment outside you is only part of the story', paragraphs: ['What happened around you: A message arrived: “Can we talk later?”', 'What happened inside you: That depends on the person.', 'The message is the same. The response may be completely different. Something inside each person is responding to and interpreting the moment. For now, just notice that something happened.'] },
  { id: 'teaching', eyebrow: 'PAY ATTENTION', title: 'Before you change a reaction, notice it', paragraphs: ['Most of us are very aware of what happens around us and much less aware of what happens inside us. Someone says something and we become defensive. Plans change and we become irritated. Someone does not respond to a message and our mind starts working. We are criticized and immediately begin explaining ourselves.', 'Often the internal movement happens so quickly that we move from the event directly into our response without noticing what occurred between the two.', 'The first goal is not to fix your reactions. It is to notice them.'], reveal: { label: 'What does “notice” mean here?', text: 'Noticing means becoming aware of what is present without immediately deciding what it means or what you need to do about it.' } },
  { id: 'scripture', eyebrow: 'SCRIPTURE · LUKE 6:45', title: 'Your response can tell you something', paragraphs: ['“The good man out of the good treasure of his heart brings out that which is good, and the evil man out of the evil treasure of his heart brings out that which is evil, for out of the abundance of the heart, his mouth speaks.”', 'Jesus directs attention toward an important reality: what comes out of a person can reveal something about what is occurring within that person.'] },
  { id: 'reflection', eyebrow: 'REFLECTION', title: 'Bring one real moment to mind', paragraphs: ['Think about a recent situation when your response seemed stronger than you expected. Do not try to explain everything yet. The goal is simply to notice.'], prompt: 'What happened? What did you feel or want to do immediately? Did the reaction feel familiar? Have you responded in a similar way in other situations?' },
  { id: 'go-deeper', eyebrow: 'GO DEEPER', title: 'Look at what happened outside—and inside', paragraphs: ['What could another person have observed from the outside? What were you experiencing on the inside? Were those two things the same, or did your internal response add meaning to what happened?', 'What happens around you matters, but so does what happens within you.'] },
  { id: 'practice', eyebrow: 'PRACTICE', title: 'Try noticing this in ordinary moments', paragraphs: ['For the next few days, pay attention to moments when something inside you changes. You may notice tension, irritation, anxiety, defensiveness, withdrawal, urgency, or the desire to control a situation.', 'When you catch one of those moments, stop briefly and ask: “What just happened in me?” Then bring that moment before God without trying to force an answer.', 'A simple prayer is enough: “God, help me see what is happening in me.”'] },
  { id: 'carry-forward', eyebrow: 'CARRY FORWARD', title: 'Let noticing become a habit', paragraphs: [
    'You do not need to understand every reaction yet. For now, keep noticing the moments when something changes inside you. The more clearly you can recognize those moments, the easier it becomes to see the patterns that repeat.',
    'Give this a little time.',
    'For the next day or two, simply notice what happens in ordinary moments. You do not need to analyze anything yet.',
  ] },
];
