'use client';
import { useState } from 'react';
import type { AwakenTurn } from '../../domain/awaken-guidance';
const EXPERIENCES=[{id:'challenged',title:'Someone questioned you',text:'You were criticized, challenged, corrected, or misunderstood.'},{id:'changed',title:'Something changed unexpectedly',text:'Plans shifted, you were interrupted, delayed, or could not control what happened.'},{id:'relational',title:'You felt overlooked or left out',text:'Someone did not include you, respond to you, notice you, or seemed to choose someone else.'},{id:'positive',title:'Something went well',text:'You succeeded, were praised, received an opportunity, or suddenly had something you wanted to protect.'}] as const;
type Sample={id:string;title:string;answer:string}; type Props={onConversation?:(turns:AwakenTurn[])=>void;onKeep?:(text:string)=>void};
export function A2ExperienceInquiry({onConversation,onKeep}:Props){
const [samples,setSamples]=useState<Sample[]>([]),[selected,setSelected]=useState<(typeof EXPERIENCES)[number]|null>(null),[answer,setAnswer]=useState(''),[comparison,setComparison]=useState(''),[finished,setFinished]=useState(false);
const available=EXPERIENCES.filter(x=>!samples.some(s=>s.id===x.id));
function saveExperience(){if(!selected||!answer.trim())return;const next=[...samples,{id:selected.id,title:selected.title,answer:answer.trim()}];setSamples(next);setSelected(null);setAnswer('');onConversation?.(next.map(s=>({question:s.title,answer:s.answer})));}
if(finished)return <section className="awaken-release-moment"><h2>{comparison.trim()?'Keep what you saw.':'You can leave this open.'}</h2>{comparison.trim()?<blockquote>{comparison.trim()}</blockquote>:<p>You do not have to make these experiences add up to a pattern.</p>}</section>;
if(samples.length>=3&&!selected)return <section className="a2-experience-compare"><p className="eyebrow">LOOK ACROSS WHAT YOU SHARED</p><h2>What do you recognize?</h2><p>These were three different experiences. Do not make them match. Look at your own words together and see whether anything about the way you respond becomes easier to recognize.</p><div className="a2-experience-compare__list">{samples.map((s,i)=><div key={s.id}><span>EXPERIENCE {i+1} · {s.title}</span><p>{s.answer}</p></div>)}</div><label>What do you notice about the way you responded?<textarea value={comparison} onChange={e=>setComparison(e.target.value)} placeholder="Keep it in your own words…" /></label><div className="awaken-guided__actions"><button className="button" type="button" disabled={!comparison.trim()} onClick={()=>{onKeep?.(comparison.trim());setFinished(true)}}>Keep what I see</button><button className="button button--secondary" type="button" onClick={()=>{onKeep?.('');setFinished(true)}}>Nothing clear yet</button></div></section>;
if(selected)return <section className="a2-experience-thread"><button type="button" className="awaken-quiet-button" onClick={()=>{setSelected(null);setAnswer('')}}>← Choose a different experience</button><div className="a2-experience-thread__choice"><span>{selected.title}</span><p>{selected.text}</p></div><div className="a2-experience-answer"><label>Bring one real example to mind. What happened, and what came out of you?<textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="A few sentences are enough…" /></label><div className="awaken-guided__actions"><button className="button" type="button" disabled={!answer.trim()} onClick={saveExperience}>Keep this example</button><button className="button button--secondary" type="button" onClick={()=>setAnswer('I’m not sure')}>I’m not sure</button></div></div></section>;
return <section className="a2-experience-picker"><p className="eyebrow">{samples.length?('EXPERIENCE '+(samples.length+1)+' OF 3'):'START HERE'}</p><h2>{samples.length?'Choose a different kind of experience.':'Which of these feels familiar?'}</h2><p>{samples.length?'Pick a different kind of experience. After three, you will look at your responses together.':'Choose one you have actually experienced. You are going to explore three different kinds, then look at your responses together.'}</p>{samples.length?<div className="a2-experience-picker__kept">{samples.map((s,i)=><div key={s.id}><span>EXPERIENCE {i+1} · {s.title}</span><p>{s.answer}</p></div>)}</div>:null}<div className="a2-experience-picker__choices">{available.map(x=><button type="button" key={x.id} onClick={()=>setSelected(x)}><strong>{x.title}</strong><span>{x.text}</span></button>)}</div></section>;
}