'use client';
import { useState } from 'react';

type Props={lesson:'a2'|'a3'|'a4'};
const CONFIG={
 a2:{eyebrow:'CATCH YOURSELF BEING YOU',title:'Try another ordinary moment.',lead:'Think of a different moment when you responded almost before you realized you were doing it.',examples:['Plans changed unexpectedly and I immediately started taking over.','Someone questioned my decision and I started defending it.','A friend did not answer my message, and I kept checking my phone.'],first:'What did you catch yourself doing almost automatically?',check:'Looking back, does that response feel familiar to you?',yes:'You noticed something familiar.',carry:'Let this moment go. See if you catch another familiar response sometime.'},
 a3:{eyebrow:'SEE WHO YOU REALLY ARE',title:'Try a different moment again.',lead:'Think of a moment when you noticed yourself doing something familiar—defending, pleasing, withdrawing, controlling, proving, or something else.',example:'Someone questioned my decision and I immediately started defending it.',first:'What did you notice yourself doing?',check:'Looking at it now, what do you notice about the difference between what you did and who you are?',yes:'You can notice what you did without turning it into a definition of yourself.',carry:'Let the moment go. Notice the response without turning it into a definition of yourself.'},
 a4:{eyebrow:'REACTIONS REVEAL WHAT IS THERE',title:'One more fresh moment.',lead:'Think of another ordinary moment when something came out of you quickly—a feeling, assumption, urge, or response.',example:'Someone did not answer my message when I expected them to.',first:'What showed up in you before you had much time to think?',check:'Looking back, what stands out about what showed up in you?',yes:'You do not have to decide what it means yet.',carry:'You do not need to explain it. You are learning to notice what your reactions reveal.'},
} as const;

export function AwakenFreshMoment({lesson}:Props){
 const cfg=CONFIG[lesson]; const [moment,setMoment]=useState(''),[answer,setAnswer]=useState(''),[step,setStep]=useState<'moment'|'notice'|'check'|'done'>('moment'),[recognition,setRecognition]=useState('');
 if(step==='moment')return <section className="awaken-fresh"><p className="eyebrow">{cfg.eyebrow}</p><h2>{cfg.title}</h2><p>{cfg.lead}</p><div className="awaken-fresh__examples"><span>FOR EXAMPLE</span>{cfg.examples.map(example => <p key={example}>{example}</p>)}</div><label>Bring a different moment to mind<textarea value={moment} onChange={e=>setMoment(e.target.value)} placeholder="A short description is enough…"/></label><button className="button" disabled={!moment.trim()} onClick={()=>setStep('notice')}>Notice this moment</button></section>;
 if(step==='notice')return <section className="awaken-fresh"><p className="eyebrow">STAY WITH THIS MOMENT</p><aside><span>THE MOMENT</span><p>{moment}</p></aside><h2>{cfg.first}</h2><textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Use your own words…"/><button className="button" disabled={!answer.trim()} onClick={()=>setStep('check')}>Keep noticing</button></section>;
 if(step==='check')return <section className="awaken-recognition-check"><p className="eyebrow">LOOK BACK FOR A MOMENT</p><p className="awaken-recognition-check__context">You stayed with one real moment and noticed what you could. Before you move on, take a second look at what you just wrote.</p><h2>{cfg.check}</h2><div className="awaken-recognition-check__choices"><button className="button" onClick={()=>{setRecognition('yes');setStep('done')}}>Yes, I can see that</button><button className="awaken-quiet-button" onClick={()=>{setRecognition('beginning');setStep('done')}}>I'm beginning to</button><button className="awaken-quiet-button" onClick={()=>setStep('notice')}>Not really yet</button></div></section>;
 return <section className="awaken-release-moment"><p className="eyebrow">THAT IS ENOUGH FOR NOW</p><h2>{recognition==='yes'?cfg.yes:'You are beginning to see it.'}</h2><div className="awaken-release-moment__glimpse"><span>WHAT YOU NOTICED</span><blockquote>“{answer}”</blockquote></div><p className="awaken-release-moment__carry">{cfg.carry}</p></section>;
}
